/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\cxk-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-44e18245",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44e18245").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-23e44f49",
    path: "/cxk/welcome.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23e44f49").then(next)
    },
  },
  {
    name: "v-bfef60fa",
    path: "/javascript/pubsub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bfef60fa").then(next)
    },
  },
  {
    name: "v-7013fb7b",
    path: "/javascript/AbortController.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7013fb7b").then(next)
    },
  },
  {
    name: "v-719f7523",
    path: "/javascript/pipe.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-719f7523").then(next)
    },
  },
  {
    name: "v-76fd1ea6",
    path: "/javascript/extendClass/extendClass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76fd1ea6").then(next)
    },
  },
  {
    name: "v-932e897c",
    path: "/javascript/useInit/useInit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-932e897c").then(next)
    },
  },
  {
    name: "v-2453ed14",
    path: "/javascript/useLockFn/useLockFn.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2453ed14").then(next)
    },
  },
  {
    name: "v-e9044d04",
    path: "/javascript/useOnce/useOnce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e9044d04").then(next)
    },
  },
  {
    name: "v-5942836e",
    path: "/plugins/plugins.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5942836e").then(next)
    },
  },
  {
    name: "v-71b4d9bc",
    path: "/react/HooksClosureProblem/demo1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71b4d9bc").then(next)
    },
  },
  {
    name: "v-11e29839",
    path: "/react/antd/ProComponent/ProTable.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11e29839").then(next)
    },
  },
  {
    name: "v-75edf4f8",
    path: "/react/antd/RequestButton.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75edf4f8").then(next)
    },
  },
  {
    name: "v-4d0588bc",
    path: "/react/hooks/useComputed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d0588bc").then(next)
    },
  },
  {
    name: "v-26b0c32b",
    path: "/react/sourceCode/hooks/useEffect.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26b0c32b").then(next)
    },
  },
  {
    name: "v-0eb70949",
    path: "/utils/utils.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0eb70949").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]