/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "cxk",
  "description": "cxknmsl",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/akebi.jpg",
        "heroText": "Hero 标题2",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/test/test/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-099d9706",
      "path": "/"
    },
    {
      "title": "JavaScript类的扩展 ###",
      "frontmatter": {},
      "regularPath": "/javascript/extendClass/extendClass.html",
      "relativePath": "javascript/extendClass/extendClass.md",
      "key": "v-2a8e10eb",
      "path": "/javascript/extendClass/extendClass.html",
      "headers": [
        {
          "level": 3,
          "title": "JavaScript类的扩展",
          "slug": "javascript类的扩展"
        }
      ]
    },
    {
      "title": "PubSub的实现 ###",
      "frontmatter": {},
      "regularPath": "/javascript/pubsub.html",
      "relativePath": "javascript/pubsub.md",
      "key": "v-57b4ea96",
      "path": "/javascript/pubsub.html",
      "headers": [
        {
          "level": 3,
          "title": "PubSub的实现",
          "slug": "pubsub的实现"
        }
      ]
    },
    {
      "title": "AbortController优雅实现取消监听(取代removeEventListener) ###",
      "frontmatter": {},
      "regularPath": "/javascript/AbortController.html",
      "relativePath": "javascript/AbortController.md",
      "key": "v-26bf8e2d",
      "path": "/javascript/AbortController.html",
      "headers": [
        {
          "level": 3,
          "title": "AbortController优雅实现取消监听(取代removeEventListener)",
          "slug": "abortcontroller优雅实现取消监听-取代removeeventlistener"
        }
      ]
    },
    {
      "title": "useLockFn函数(竞态锁) ###",
      "frontmatter": {},
      "regularPath": "/javascript/useLockFn/useLockFn.html",
      "relativePath": "javascript/useLockFn/useLockFn.md",
      "key": "v-0596900a",
      "path": "/javascript/useLockFn/useLockFn.html",
      "headers": [
        {
          "level": 3,
          "title": "useLockFn函数(竞态锁)",
          "slug": "uselockfn函数-竞态锁"
        }
      ]
    },
    {
      "title": "useOnce函数 在生命周期内只会令其回调运行1次的hooks ###",
      "frontmatter": {},
      "regularPath": "/javascript/useOnce/useOnce.html",
      "relativePath": "javascript/useOnce/useOnce.md",
      "key": "v-14ae177a",
      "path": "/javascript/useOnce/useOnce.html",
      "headers": [
        {
          "level": 3,
          "title": "useOnce函数 在生命周期内只会令其回调运行1次的hooks",
          "slug": "useonce函数-在生命周期内只会令其回调运行1次的hooks"
        }
      ]
    },
    {
      "title": "devConst ##",
      "frontmatter": {},
      "regularPath": "/plugins/plugins.html",
      "relativePath": "plugins/plugins.md",
      "key": "v-b1855a16",
      "path": "/plugins/plugins.html",
      "headers": [
        {
          "level": 2,
          "title": "devConst",
          "slug": "devconst"
        },
        {
          "level": 2,
          "title": "代理console",
          "slug": "代理console"
        }
      ]
    },
    {
      "title": "useInit缓存函数 ###",
      "frontmatter": {},
      "regularPath": "/javascript/useInit/useInit.html",
      "relativePath": "javascript/useInit/useInit.md",
      "key": "v-2093d607",
      "path": "/javascript/useInit/useInit.html",
      "headers": [
        {
          "level": 3,
          "title": "useInit缓存函数",
          "slug": "useinit缓存函数"
        }
      ]
    },
    {
      "title": "我遇到的React Hooks中的闭包问题 (关键词: 函数词法作用域)",
      "frontmatter": {},
      "regularPath": "/react/HooksClosureProblem/demo1.html",
      "relativePath": "react/HooksClosureProblem/demo1.md",
      "key": "v-f436cb96",
      "path": "/react/HooksClosureProblem/demo1.html",
      "headers": [
        {
          "level": 3,
          "title": "我遇到的React Hooks中的闭包问题 (关键词: 函数词法作用域)",
          "slug": "我遇到的react-hooks中的闭包问题-关键词-函数词法作用域"
        }
      ]
    },
    {
      "title": "useComputed ###",
      "frontmatter": {},
      "regularPath": "/react/hooks/useComputed.html",
      "relativePath": "react/hooks/useComputed.md",
      "key": "v-759b0075",
      "path": "/react/hooks/useComputed.html",
      "headers": [
        {
          "level": 3,
          "title": "useComputed",
          "slug": "usecomputed"
        }
      ]
    },
    {
      "title": "useEffect ###",
      "frontmatter": {},
      "regularPath": "/react/sourceCode/hooks/useEffect.html",
      "relativePath": "react/sourceCode/hooks/useEffect.md",
      "key": "v-c7d22506",
      "path": "/react/sourceCode/hooks/useEffect.html",
      "headers": [
        {
          "level": 3,
          "title": "useEffect",
          "slug": "useeffect"
        }
      ]
    },
    {
      "title": "ProTable ###",
      "frontmatter": {},
      "regularPath": "/react/antd/ProComponent/ProTable.html",
      "relativePath": "react/antd/ProComponent/ProTable.md",
      "key": "v-9293c076",
      "path": "/react/antd/ProComponent/ProTable.html",
      "headers": [
        {
          "level": 3,
          "title": "ProTable",
          "slug": "protable"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/test/test.html",
      "relativePath": "test/test.md",
      "key": "v-72930975",
      "path": "/test/test.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "test页面",
        "link": "/test/test"
      }
    ],
    "sidebar": [
      [
        "/",
        "首页"
      ],
      [
        "/test/test",
        "test页面"
      ],
      {
        "title": "JavaScript",
        "children": [
          [
            "/javascript/extendClass/extendClass.md",
            "类的扩展"
          ],
          [
            "/javascript/pubsub.md",
            "发布订阅(PubSub)"
          ],
          [
            "/javascript/useInit/useInit.md",
            "useInit函数"
          ],
          [
            "/javascript/useLockFn/useLockFn.md",
            "useLockFn函数(竞态锁)"
          ],
          [
            "/javascript/useOnce/useOnce.md",
            "useOnce函数"
          ],
          [
            "/javascript/AbortController.md",
            "使用AbortController优雅销毁监听"
          ]
        ]
      },
      {
        "title": "React",
        "children": [
          {
            "title": "Hooks",
            "children": [
              [
                "/react/hooks/useComputed.md",
                "useComputed"
              ]
            ]
          },
          {
            "title": "React源码部分",
            "children": [
              {
                "title": "Hooks",
                "children": [
                  [
                    "/react/sourceCode/hooks/useEffect.md",
                    "useEffect"
                  ]
                ]
              }
            ]
          },
          {
            "title": "ant design",
            "children": [
              {
                "title": "ProComponent",
                "children": [
                  [
                    "/react/antd/ProComponent/ProTable.md",
                    "ProTable"
                  ]
                ]
              }
            ]
          },
          {
            "title": "Hooks闭包陷阱",
            "children": [
              [
                "/react/HooksClosureProblem/demo1.md",
                "useMemo控制ui导致的闭包陷阱"
              ]
            ]
          }
        ]
      },
      [
        "/plugins/plugins.md",
        "用于开发的小技巧"
      ]
    ]
  }
}