/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "只因你太美",
  "description": " ",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/akebi.jpg",
        "actionText": "进入博客 →",
        "actionLink": "/javascript/extendClass/extendClass"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-44e18245",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/cxk/welcome.html",
      "relativePath": "cxk/welcome.md",
      "key": "v-23e44f49",
      "path": "/cxk/welcome.html"
    },
    {
      "title": "PubSub的实现 ###",
      "frontmatter": {},
      "regularPath": "/javascript/pubsub.html",
      "relativePath": "javascript/pubsub.md",
      "key": "v-bfef60fa",
      "path": "/javascript/pubsub.html",
      "headers": [
        {
          "level": 3,
          "title": "PubSub的实现",
          "slug": "pubsub的实现"
        }
      ]
    },
    {
      "title": "AbortController优雅实现取消监听(取代removeEventListener) ###",
      "frontmatter": {},
      "regularPath": "/javascript/AbortController.html",
      "relativePath": "javascript/AbortController.md",
      "key": "v-7013fb7b",
      "path": "/javascript/AbortController.html",
      "headers": [
        {
          "level": 3,
          "title": "AbortController优雅实现取消监听(取代removeEventListener)",
          "slug": "abortcontroller优雅实现取消监听-取代removeeventlistener"
        }
      ]
    },
    {
      "title": "pipe函数 ###",
      "frontmatter": {},
      "regularPath": "/javascript/pipe.html",
      "relativePath": "javascript/pipe.md",
      "key": "v-719f7523",
      "path": "/javascript/pipe.html",
      "headers": [
        {
          "level": 3,
          "title": "pipe函数",
          "slug": "pipe函数"
        }
      ]
    },
    {
      "title": "JavaScript类的扩展 ###",
      "frontmatter": {},
      "regularPath": "/javascript/extendClass/extendClass.html",
      "relativePath": "javascript/extendClass/extendClass.md",
      "key": "v-76fd1ea6",
      "path": "/javascript/extendClass/extendClass.html",
      "headers": [
        {
          "level": 3,
          "title": "JavaScript类的扩展",
          "slug": "javascript类的扩展"
        }
      ]
    },
    {
      "title": "useInit缓存函数 ###",
      "frontmatter": {},
      "regularPath": "/javascript/useInit/useInit.html",
      "relativePath": "javascript/useInit/useInit.md",
      "key": "v-932e897c",
      "path": "/javascript/useInit/useInit.html",
      "headers": [
        {
          "level": 3,
          "title": "useInit缓存函数",
          "slug": "useinit缓存函数"
        }
      ]
    },
    {
      "title": "useLockFn函数(竞态锁) ###",
      "frontmatter": {},
      "regularPath": "/javascript/useLockFn/useLockFn.html",
      "relativePath": "javascript/useLockFn/useLockFn.md",
      "key": "v-2453ed14",
      "path": "/javascript/useLockFn/useLockFn.html",
      "headers": [
        {
          "level": 3,
          "title": "useLockFn函数(竞态锁)",
          "slug": "uselockfn函数-竞态锁"
        }
      ]
    },
    {
      "title": "useOnce函数 在生命周期内只会令其回调运行1次的hooks ###",
      "frontmatter": {},
      "regularPath": "/javascript/useOnce/useOnce.html",
      "relativePath": "javascript/useOnce/useOnce.md",
      "key": "v-e9044d04",
      "path": "/javascript/useOnce/useOnce.html",
      "headers": [
        {
          "level": 3,
          "title": "useOnce函数 在生命周期内只会令其回调运行1次的hooks",
          "slug": "useonce函数-在生命周期内只会令其回调运行1次的hooks"
        }
      ]
    },
    {
      "title": "devConst ##",
      "frontmatter": {},
      "regularPath": "/plugins/plugins.html",
      "relativePath": "plugins/plugins.md",
      "key": "v-5942836e",
      "path": "/plugins/plugins.html",
      "headers": [
        {
          "level": 2,
          "title": "devConst",
          "slug": "devconst"
        },
        {
          "level": 2,
          "title": "代理console",
          "slug": "代理console"
        }
      ]
    },
    {
      "title": "我遇到的React Hooks中的闭包问题 (关键词: 函数词法作用域)",
      "frontmatter": {},
      "regularPath": "/react/HooksClosureProblem/demo1.html",
      "relativePath": "react/HooksClosureProblem/demo1.md",
      "key": "v-71b4d9bc",
      "path": "/react/HooksClosureProblem/demo1.html",
      "headers": [
        {
          "level": 3,
          "title": "我遇到的React Hooks中的闭包问题 (关键词: 函数词法作用域)",
          "slug": "我遇到的react-hooks中的闭包问题-关键词-函数词法作用域"
        }
      ]
    },
    {
      "title": "ProTable ###",
      "frontmatter": {},
      "regularPath": "/react/antd/ProComponent/ProTable.html",
      "relativePath": "react/antd/ProComponent/ProTable.md",
      "key": "v-11e29839",
      "path": "/react/antd/ProComponent/ProTable.html",
      "headers": [
        {
          "level": 3,
          "title": "ProTable",
          "slug": "protable"
        }
      ]
    },
    {
      "title": "RequestButton ###",
      "frontmatter": {},
      "regularPath": "/react/antd/RequestButton.html",
      "relativePath": "react/antd/RequestButton.md",
      "key": "v-75edf4f8",
      "path": "/react/antd/RequestButton.html",
      "headers": [
        {
          "level": 3,
          "title": "RequestButton",
          "slug": "requestbutton"
        }
      ]
    },
    {
      "title": "useComputed ###",
      "frontmatter": {},
      "regularPath": "/react/hooks/useComputed.html",
      "relativePath": "react/hooks/useComputed.md",
      "key": "v-4d0588bc",
      "path": "/react/hooks/useComputed.html",
      "headers": [
        {
          "level": 3,
          "title": "useComputed",
          "slug": "usecomputed"
        }
      ]
    },
    {
      "title": "useEffect ###",
      "frontmatter": {},
      "regularPath": "/react/sourceCode/hooks/useEffect.html",
      "relativePath": "react/sourceCode/hooks/useEffect.md",
      "key": "v-26b0c32b",
      "path": "/react/sourceCode/hooks/useEffect.html",
      "headers": [
        {
          "level": 3,
          "title": "useEffect",
          "slug": "useeffect"
        }
      ]
    },
    {
      "title": "个人开发常用工具函数 ###",
      "frontmatter": {},
      "regularPath": "/utils/utils.html",
      "relativePath": "utils/utils.md",
      "key": "v-0eb70949",
      "path": "/utils/utils.html",
      "headers": [
        {
          "level": 3,
          "title": "个人开发常用工具函数",
          "slug": "个人开发常用工具函数"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebar": [
      {
        "title": "JavaScript",
        "children": [
          [
            "/javascript/extendClass/extendClass.md",
            "类的扩展"
          ],
          [
            "/javascript/pubsub.md",
            "发布订阅(PubSub)"
          ],
          [
            "/javascript/useInit/useInit.md",
            "useInit函数"
          ],
          [
            "/javascript/useLockFn/useLockFn.md",
            "useLockFn函数(竞态锁)"
          ],
          [
            "/javascript/useOnce/useOnce.md",
            "useOnce函数"
          ],
          [
            "/javascript/AbortController.md",
            "使用AbortController优雅销毁监听"
          ],
          [
            "/javascript/pipe.md",
            "使用pipe函数优雅的管理多个条件执行的回调"
          ]
        ]
      },
      {
        "title": "React",
        "children": [
          {
            "title": "Hooks",
            "children": [
              [
                "/react/hooks/useComputed.md",
                "useComputed"
              ]
            ]
          },
          {
            "title": "React源码部分",
            "children": [
              {
                "title": "Hooks",
                "children": [
                  [
                    "/react/sourceCode/hooks/useEffect.md",
                    "useEffect"
                  ]
                ]
              }
            ]
          },
          {
            "title": "ant design",
            "children": [
              {
                "title": "ProComponent",
                "children": [
                  [
                    "/react/antd/ProComponent/ProTable.md",
                    "ProTable"
                  ]
                ]
              },
              [
                "/react/antd/RequestButton.md",
                "RequestButton"
              ]
            ]
          },
          {
            "title": "Hooks闭包陷阱",
            "children": [
              [
                "/react/HooksClosureProblem/demo1.md",
                "useMemo控制ui导致的闭包陷阱"
              ]
            ]
          }
        ]
      },
      [
        "/plugins/plugins.md",
        "用于开发的小技巧"
      ],
      {
        "title": "utils",
        "children": [
          [
            "/utils/utils.md",
            "个人常用工具函数库"
          ]
        ]
      }
    ]
  }
}