/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "cxk",
  "description": "cxknmsl",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "class SuperArray ###",
      "frontmatter": {},
      "regularPath": "/javascript/ArraySet/ArraySet.html",
      "relativePath": "javascript/ArraySet/ArraySet.md",
      "key": "v-3643048e",
      "path": "/javascript/ArraySet/ArraySet.html",
      "headers": [
        {
          "level": 3,
          "title": "class SuperArray",
          "slug": "class-superarray"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/akebi.jpg",
        "heroText": "Hero 标题2",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/test/test/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1c7f9382",
      "path": "/"
    },
    {
      "title": "PubSub的实现 ###",
      "frontmatter": {},
      "regularPath": "/javascript/pubsub.html",
      "relativePath": "javascript/pubsub.md",
      "key": "v-4f25769c",
      "path": "/javascript/pubsub.html",
      "headers": [
        {
          "level": 3,
          "title": "PubSub的实现",
          "slug": "pubsub的实现"
        }
      ]
    },
    {
      "title": "useInit缓存函数 ###",
      "frontmatter": {},
      "regularPath": "/javascript/useInit/useInit.html",
      "relativePath": "javascript/useInit/useInit.md",
      "key": "v-764d362e",
      "path": "/javascript/useInit/useInit.html",
      "headers": [
        {
          "level": 3,
          "title": "useInit缓存函数",
          "slug": "useinit缓存函数"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/test/test.html",
      "relativePath": "test/test.md",
      "key": "v-1ac4b948",
      "path": "/test/test.html"
    },
    {
      "title": "useComputed ###",
      "frontmatter": {},
      "regularPath": "/react/hooks/useComputed.html",
      "relativePath": "react/hooks/useComputed.md",
      "key": "v-2d656c48",
      "path": "/react/hooks/useComputed.html",
      "headers": [
        {
          "level": 3,
          "title": "useComputed",
          "slug": "usecomputed"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "test页面",
        "link": "/test/test"
      }
    ],
    "sidebar": [
      [
        "/",
        "首页"
      ],
      [
        "/test/test",
        "test页面"
      ],
      {
        "title": "JavaScript",
        "children": [
          [
            "/javascript/ArraySet/ArraySet.md",
            "ArraySet"
          ],
          [
            "/javascript/pubsub.md",
            "发布订阅(PubSub)"
          ],
          [
            "/javascript/useInit/useInit.md",
            "useInit函数"
          ]
        ]
      },
      {
        "title": "React",
        "children": [
          {
            "title": "hooks",
            "children": [
              [
                "/react/hooks/useComputed.md",
                "useComputed"
              ]
            ]
          }
        ]
      }
    ]
  }
}